import { Metadata } from "next"

// chứa bố cụ chung
export const metadata: Metadata = {
  // title: 'Next.js',
  title: {
    default:"next js tutorial-codeding",
    template: "%s | tutorial-codeding",
  },
  // description: '...': 
  // Sẽ tạo ra thẻ <meta name="description" content="Generated by Next.js" />.
  //  Đây là dòng mô tả ngắn về trang web, 
  // thường được các công cụ tìm kiếm như Google hiển thị bên dưới tiêu đề trong kết quả tìm kiếm.
  description: 'Generated by Next.js',
}

export default function RootLayout({
  // là một prop (thuộc tính) đặc biệt trong React. 
  // Trong Next.js, children chính là nơi nội dung của các trang con (từ các file page.js) 
  // hoặc các layout lồng nhau sẽ được hiển thị.
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <header style={{
           backgroundColor: 'lightblue',
           padding: '10px',
        }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{
           backgroundColor: 'lightblue',
           padding: '10px',
        }}>
          <p>footer</p>
        </footer>
      </body>
    </html>
  )
}
